ARG NODEJS_VERSION

FROM node:${NODEJS_VERSION}

ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG CERTIFICATE_FILE
ARG CERTIFICATE_KEY
ARG CERTIFICATE_CHAIN
ARG NODEJS_ENV
ARG NODEJS_DOMAIN
ARG NODEJS_IP
ARG NODEJS_PATH_STATIC
ARG NODEJS_DEBUG
ARG NODEJS_DIGEST
ARG NODEJS_ENCRYPTION_SECRET
ARG NODEJS_ENCRYPTION_KEY
ARG NODEJS_PORT_HTTP
ARG NODEJS_PORT_HTTPS

ENV NODE_ENV=${NODEJS_ENV}
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/entrypoint_nodejs.sh /usr/local/bin/entrypoint.sh

# System
RUN cd ~ \
&& ln -s ~/ /home/link_root \
&& chmod +x /usr/local/bin/entrypoint.sh \
&& apt-get update && apt-get install -y \
software-properties-common \
apt-transport-https \
lsb-release \
sudo \
nano \
tzdata \
curl \
make \
git \
zip \
unzip \
cron \
wget \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Npm
&& npm install -g selenium-side-runner chromedriver --unsafe-perm=true --allow-root \
# Selenium
&& curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
&& add-apt-repository "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
&& apt-get update && apt-get install -y google-chrome-stable \
# Clean
&& rm /etc/apt/sources.list.d/google-chrome.list \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE ${NODEJS_PORT_HTTP} ${NODEJS_PORT_HTTPS}
