ARG NEXTCLOUD_VERSION

FROM nextcloud:${NEXTCLOUD_VERSION}-fpm

ARG WWW_USER_NAME
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV NEXTCLOUD_UPDATE=1

COPY ${PATH_ROOT}/supervisord.conf /

# System
RUN cd ~ \
&& chmod +x /usr/local/bin/entrypoint.sh \
&& apt-get update && apt-get install -y \
sudo \
nano \
tzdata \
curl \
make \
git \
zip \
unzip \
cron \
wget \
supervisor \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Supervisor
&& mkdir /var/log/supervisord /var/run/supervisord \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]

EXPOSE ${NEXTCLOUD_PORT}