ARG NEXTCLOUD_OS_VERSION

FROM ubuntu:${NEXTCLOUD_OS_VERSION}

ARG USER_NAME
ARG USER_PASSWORD
ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/entrypoint_nextcloud.sh /usr/local/bin/entrypoint.sh
COPY ${PATH_ROOT}/setup-nextcloud.php /home/setup-nextcloud.php

# System
RUN cd ~ \
&& chmod +x /usr/local/bin/entrypoint.sh \
&& apt-get update && apt-get install -y \
sudo \
nano \
tzdata \
curl \
make \
git \
zip \
unzip \
cron \
wget \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# User sudo
&& useradd --home /home/${USER_NAME} -g sudo --shell /bin/bash -m ${USER_NAME} \
&& echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd \
# User www
&& useradd --home /home/${WWW_USER_NAME} -g ${WEB_USER_GROUP} --shell /bin/false -m ${WWW_USER_NAME} \
&& echo "${WWW_USER_NAME}:${WWW_USER_PASSWORD}" | chpasswd \
&& chown root:root /home/${WWW_USER_NAME} \
&& mkdir /home/${WWW_USER_NAME}/root \
# Setup
&& mkdir -p /home${WWW_USER_NAME}/root${WEB_PATH}nextcloud \
&& cp /home/setup-nextcloud.php /home${WWW_USER_NAME}/root${WEB_PATH}nextcloud/setup-nextcloud.php \
&& chmod 775 /home/${WWW_USER_NAME}/root${WEB_PATH}nextcloud \
&& chown ${USER_NAME}:${WEB_USER_GROUP} /home/${WWW_USER_NAME}/root${WEB_PATH}nextcloud \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]