ARG APACHE_VERSION

FROM httpd:${APACHE_VERSION}

ARG WWW_USER_NAME
ARG WWW_USER_PASSWORD
ARG WEB_USER_GROUP
ARG WEB_PATH
ARG PATH_ROOT
ARG TIMEZONE
ARG CERTIFICATE_FILE
ARG CERTIFICATE_KEY
ARG CERTIFICATE_CHAIN
ARG DOMAIN
ARG APACHE_PORT_HTTP
ARG APACHE_PORT_HTTPS
ARG APACHE_PATH_ROOT
ARG APACHE_GITLAB_PORT
ARG APACHE_GITLAB_PORT_UNICORN
ARG APACHE_GITLAB_DATA_PATH
ARG PHP7_PORT_FPM
ARG PHP7_VH_NAME

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ${PATH_ROOT}/httpd.conf ${APACHE_PATH_ROOT}/conf/httpd.conf

# System
RUN cd ~ \
&& apt-get update && apt-get install -y \
sudo \
nano \
tzdata \
curl \
make \
git \
zip \
unzip \
cron \
wget \
apache2-utils \
# Time
&& ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata \
# Gitlab
&& curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash \
&& apt-get install gitlab-ce -y \
&& gitlab-ctl stop \
&& > /etc/gitlab/gitlab.rb \
&& echo "\n\n \
external_url 'https://gitlab.${DOMAIN}' \n \
git_data_dirs({"default" => {"path" => "${APACHE_GITLAB_DATA_PATH}"}}) \n \
gitlab_workhorse['listen_network'] = "tcp" \n \
gitlab_workhorse['listen_addr'] = “127.0.0.1:${APACHE_GITLAB_PORT}” \n \
unicorn['listen'] = '127.0.0.1' \n \
unicorn['port'] = ${APACHE_GITLAB_PORT_UNICORN} \n \
unicorn['socket'] = '/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket' \n \
web_server['external_users'] = ['www-data'] \n \
nginx['enable'] = false" >> /etc/gitlab/gitlab.rb \
&& gitlab-ctl reconfigure \
# Clean
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean -y \
&& apt-get autoclean -y \
&& apt-get autoremove -y

EXPOSE ${APACHE_PORT_HTTP} ${APACHE_PORT_HTTPS}